name: tests
on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库代码
      - name: Checkout the repository
        uses: actions/checkout@v2

      # 设置 JDK 版本，确保与 pom.xml 中的版本一致
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # 缓存 Maven 包
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 使用 Maven 运行测试
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
